language: python

python:
  - "3.5"

env:
  # - TOX_ENV=flake8
  # - TOX_ENV=py27
  # - TOX_ENV=py33
  # - TOX_ENV=py34
  # - TOX_ENV=py35
  # - TOX_ENV=mkdocs DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
  - TOX_ENV=mkdocs DEPLOY_DOCS="true"

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; make gh-deploy ; git log -n 2 --branches gh-pages ; echo "Completed deploying documentation" ; fi
